aws-samples/aws-ai-ml-workshop-kr

.gitignore, src/release/2018-11/README.md, src/release/2018-11/lambda_function.py, src/release/2018-11/module10-mxnet_cifar10_with_gluon.ipynb, src/release/2018-11/module11-Image-classification-transfer-learning-highlevel.ipynb, src/release/2018-11/module12-object_detection_incremental_training.ipynb, src/release/2018-11/module13-HPO_Analyze_TuningJob_Results.ipynb, src/release/2018-11/module3-video-game-sales-xgboost.ipynb, src/release/2018-11/module4-TensorFlow_Distributed_MNIST.ipynb, src/release/2018-11/module5-Image-classification-transfer-learning.ipynb, src/release/2018-11/module6-DeepAR-HomeElectricity.ipynb, src/release/2018-11/module7-Movie recommendation on Amazon SageMaker Using Factorization Machines.ipynb, src/release/2018-11/module8-SageMaker-Seq2Seq-Translation-English-German-InternetFacingApp.ipynb, src/release/2018-11/module9-two_layer_net_nn.ipynb, src/release/2018-11/sample_query.json
=> Nov. 2018 updates

contribution/daekeun-ml/blazingtext-korean-workshop/blazingtext_endpoint_api_gateway.md, contribution/daekeun-ml/blazingtext-korean-workshop/data/lifecycle-config.txt, contribution/daekeun-ml/blazingtext-korean-workshop/get_started.md
=> Modified HoL Guideline 

contribution/daekeun-ml/blazingtext-korean-workshop/blazingtext_endpoint_api_gateway.md, contribution/daekeun-ml/blazingtext-korean-workshop/get_started.md
=> Fixed Typos

genai/workshop/utils/common.py
update restapi_id for tech-summit lab sessions
=> update restapi_id for tech-summit lab sessions

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/bedrock.py, genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/streamlit.py
=> Update web_ui & BE code

neuron/hf-optimum/03-Chatboat-SOLAR-10.7B-Inf2/SOLAR-10.7b-chatbot.ipynb, neuron/transformers-neuronx/SOLAR-10.7B-Instruct-v1.0-sampling.ipynb
add SOLAR 10.7B examples for the customer support
=> add SOLAR 10.7B examples

genai/genai-app-demo/01-prompt-engineering-demo/README.md
=> bedrock demo korean README 

sagemaker/byom/01-scikit-sagemaker-inference-retail-analysis/Readme.md
Added file Readme.dm. 
Thank you.
=> add md comment

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/bedrock.py, genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/streamlit.py
=> Add new UI (under construction, but working ^^..)

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/streamlit.py
Add a new streamlit UI for previous log 
=> Add a new streamlit UI for previous log 

genai/aws-gen-ai-kr/40_inference/10-Getting-Started/01-deploy-Llama-2-7B-SageMaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/02-deploy-Mistral-7B-Sagemaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/03-deploy-Solar-10.7B-SageMaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/04-deploy-Open-Solar-10.7B-SageMaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/05-deploy-Finetuned-Llama-2-Sagemaker-Endpoint-inf2.ipynb
Adding deploying LLM models to g5.24xl and inf2.48xl using Sagemaker
01-deploy-Llama-2-7B-SageMaker-Endpoint-g5.ipynb
02-deploy-Mistral-7B-Sagemaker-Endpoint-g5.ipynb
03-deploy-Solar-10.7B-SageMaker-Endpoint-g5.ipynb
04-deploy-Open-Solar-10.7B-SageMaker-Endpoint-g5.ipynb
05-deploy-Finetuned-Llama-2-Sagemaker-Endpoint-inf2.ipynb
=> deploy-llm-models-joohyery-240423

genai/aws-gen-ai-kr/40_inference/10-Getting-Started/01-deploy-Llama-2-7B-SageMaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/02-deploy-Mistral-7B-Sagemaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/03-deploy-Solar-10.7B-SageMaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/04-deploy-Open-Solar-10.7B-SageMaker-Endpoint-g5.ipynb
=> deploy-llm-models-joohyery-240423-v3-remove-HF-token

genai/aws-gen-ai-kr/40_inference/10-Getting-Started/01-deploy-Llama-2-7B-SageMaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/02-deploy-Mistral-7B-Sagemaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/03-deploy-Solar-10.7B-SageMaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/04-deploy-Open-Solar-KO-10.7B-SageMaker-Endpoint-g5.ipynb, genai/aws-gen-ai-kr/40_inference/10-Getting-Started/05-deploy-Finetuned-Llama-2-Sagemaker-Endpoint-inf2.ipynb
=> deploy-llm-models-joohyery-240423-add-guide

genai/aws-gen-ai-kr/utils/rag_summit.py
Hugggggeee thanks to Dongjin~~~
=> [Fix] : fix HyDE RAG fusion error

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/bedrock.py, genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/streamlit.py
=> [Add] : add HyDE RAG Fusion mid context

genai/aws-gen-ai-kr/utils/rag_summit.py
=> [Fix] : fix no parent doc error

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/bedrock.py, genai/aws-gen-ai-kr/utils/rag_summit.py
=> [Fix] : fix context error

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/bedrock.py, genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/requirements.txt, genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/streamlit.py, genai/aws-gen-ai-kr/utils/rag_summit.py
=> [Add] : add .51 as initial hybridsearch, update rag

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/bedrock.py
=> [Fix] : change k value to 7

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/04_web_ui/requirements.txt
=> [04 web_ui] Add missing package to requirement.txt

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/02_rag/02_rag_reranker.ipynb
*Description of changes:* Minor typo correction 
=> Typo update 02_rag_reranker.ipynb

genai/aws-gen-ai-kr/00_setup/setup_kr.ipynb, genai/aws-gen-ai-kr/00_setup/setup_opensearch_simple_kr.ipynb
- Refactored setup code for foreign customer
=> Update setup for Gen AI chatbot 

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/chatbot_eng/04_web_ui/bedrock.py, genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/chatbot_eng/04_web_ui/requirements.txt, genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/chatbot_eng/04_web_ui/streamlit.py
=> [Fix] : fix chatbot application

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/chatbot_eng/00_Setup_OpenSearch_Access/setup_opensearch_access.ipynb
- Implement functionality to check OpenSearch domain address
- Add code to allow users to easily verify the domain address
=> feat: Add code to verify OpenSearch domain address

genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/chatbot_eng/02_rag/05_rag_parent_document.ipynb, genai/aws-gen-ai-kr/20_applications/02_qa_chatbot/chatbot_eng/04_web_ui/bedrock.py
=> [Modify] : Bedrock Temperature to 0, 05 rag update

genai/aws-gen-ai-kr/30_fine_tune/03-fine-tune-llama3/llama3-2/setup/README.md
Update wrong command in llama3.2 fine tuning setup guide
=> Update setup guide (llama3.2 fine tuning)

genai/aws-gen-ai-kr/20_applications/19_agentic_rag/02_opensearch_basic/README.md
OpenSearch 기본 사항에 대한 업데이트 입니다.
=> OpenSearch 기본 사항에 대한 업데이트 입니다.
